name: anom

channels:
  - conda-forge
  - default

dependencies:
  - python=3.6
  - sphinx=1.5.3
  - pip:
      - google-cloud-datastore==0.23.0
      - python-dateutil==2.6.0
      - sphinxcontrib-napoleon
