language: python
python:
- '3.6'
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1 CLOUDSDK_PYTHON=$(which python2) GOOGLE_APPLICATION_CREDENTIALS=credentials.json
before_install:
- openssl aes-256-cbc -K $encrypted_012a989fbf28_key -iv $encrypted_012a989fbf28_iv
  -in tests/credentials.tar.gz.enc -out tests/credentials.tar.gz -d
- curl https://sdk.cloud.google.com | bash
- tar -xzf tests/credentials.tar.gz
- gcloud -q components update beta
- gcloud -q components update cloud-datastore-emulator
- gcloud -q config set project anom-ci
- gcloud auth activate-service-account --key-file credentials.json
install:
- pip install -r requirements-dev.txt
script:
- py.test
services:
- memcached
